export let LTL_DESCRIPTION = 'LTL means linear temporal logic'
export let UNKNOWN_INTENT = 'I did not understand you'
export let MODEL_SEND_PROMPT = 'Please send me your model as a JSON file'
export let INVALID_JSON = (msg: string) => `Your uploaded file is not valid JSON (Error: ${msg})`
export let TOO_MANY_FILES = 'Please upload exactly one JSON file'
export let MODEL_RECEIVED = 'I received your model and will use it from now on'
export let TUTORIAL_SELECT_PROMPT = 'Which tutorial would you like to do?'
export let TUTORIAL_START_PROMPT = 'Do you like to start the tutorial?'
export let TUTORIAL_SELECT_CANCELLED = 'Tutorial selection cancelled.'
export let TUTORIAL_UNKNOWN_SELECT = 'Please input a tutorial number, or anything else to cancel.'