//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioCheck
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BioCheck.Assets.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle
        {
            get
            {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Already registered?.
        /// </summary>
        public static string AlreadyRegisteredLabel
        {
            get
            {
                return ResourceManager.GetString("AlreadyRegisteredLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to authenticating....
        /// </summary>
        public static string AuthenticatingMessage
        {
            get
            {
                return ResourceManager.GetString("AuthenticatingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        public static string BackToLoginButton
        {
            get
            {
                return ResourceManager.GetString("BackToLoginButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initializing Application.....
        /// </summary>
        public static string BusyIndicatorLoadingUser
        {
            get
            {
                return ResourceManager.GetString("BusyIndicatorLoadingUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string BusyIndicatorLoggingIn
        {
            get
            {
                return ResourceManager.GetString("BusyIndicatorLoggingIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submitting Registration....
        /// </summary>
        public static string BusyIndicatorRegisteringUser
        {
            get
            {
                return ResourceManager.GetString("BusyIndicatorRegisteringUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton
        {
            get
            {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle
        {
            get
            {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string LoginButton
        {
            get
            {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginWindowTitle
        {
            get
            {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string LogOffButton
        {
            get
            {
                return ResourceManager.GetString("LogOffButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Analysis Log.
        /// </summary>
        public static string LogWindowTitle
        {
            get
            {
                return ResourceManager.GetString("LogWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not registered yet?.
        /// </summary>
        public static string NotRegisteredYetLabel
        {
            get
            {
                return ResourceManager.GetString("NotRegisteredYetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton
        {
            get
            {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string RegisterNowButton
        {
            get
            {
                return ResourceManager.GetString("RegisterNowButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please complete all required fields to create your account.
        /// </summary>
        public static string RegistrationFormHeader
        {
            get
            {
                return ResourceManager.GetString("RegistrationFormHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegistrationWindowTitle
        {
            get
            {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        public static string RememberMeLabel
        {
            get
            {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string WelcomeMessage
        {
            get
            {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButton
        {
            get
            {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButton
        {
            get
            {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
    }
}
